import {readFile,readdir,mkdir,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
const types={html:'text/html; charset=utf-8',css:'text/css; charset=utf-8',js:'text/javascript; charset=utf-8',svg:'image/svg+xml',jpg:'image/jpeg',webp:'image/webp',woff2:'font/woff2',txt:'text/plain; charset=utf-8'};
const files={};
async function walk(dir){for(const f of await readdir(dir,{withFileTypes:true})){const p=join(dir,f.name);if(p==='public/assets/reference-large')continue;if(f.isDirectory())await walk(p);else{const key='/'+p.replace(/^public\//,'');files[key]=[(await readFile(p)).toString('base64'),types[p.split('.').pop()]||'application/octet-stream'];}}}
await walk('public');await mkdir('dist',{recursive:true});
const contactCode=(await readFile('src/contact.mjs','utf8')).replace('export async function contact','async function contact');
const worker=`${contactCode}const files=${JSON.stringify(files)};export default {async fetch(request,env){const url=new URL(request.url);let path=url.pathname;if(path.startsWith('/api/contact'))return contact(request,env);if(path==='/')path='/index.html';if(path==='/impressum'||path==='/datenschutz'||path==='/karriere')path+='.html';const headers={'X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','X-Frame-Options':'DENY','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Content-Security-Policy':"default-src 'self'; img-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'none'",'X-Robots-Tag':'noindex, nofollow'};if(!['GET','HEAD'].includes(request.method))return new Response('Method not allowed',{status:405,headers:{...headers,Allow:'GET, HEAD'}});const large=path.match(/^\\/assets\\/reference-large\\/(?:public|facades|interiors)-(\\d{3})\\.webp$/);if(large){const service=env['PHOTO'+(Number(large[1])%3)];const response=await service.fetch(request);const output=new Response(response.body,response);for(const [key,value] of Object.entries(headers))output.headers.set(key,value);return output;}const entry=files[path];if(!entry)return new Response('Seite nicht gefunden',{status:404,headers});headers['Content-Type']=entry[1];headers['Cache-Control']=path.startsWith('/assets/')?'public, max-age=86400':'public, max-age=0, must-revalidate';const body=Uint8Array.from(atob(entry[0]),c=>c.charCodeAt(0));return new Response(request.method==='HEAD'?null:body,{headers});}};`;
await writeFile('dist/worker.mjs',worker);
const photoFiles=[{},{},{}];for(const file of await readdir('public/assets/reference-large')){if(!file.endsWith('.webp'))continue;const shard=Number(file.match(/-(\d{3})\.webp$/)[1])%3;photoFiles[shard]['/assets/reference-large/'+file]=(await readFile(join('public/assets/reference-large',file))).toString('base64');}
for(let shard=0;shard<3;shard++){const code=`const files=${JSON.stringify(photoFiles[shard])};export default {async fetch(request){const path=new URL(request.url).pathname;const value=files[path];const headers={'Content-Type':'image/webp','Cache-Control':'public, max-age=86400','X-Content-Type-Options':'nosniff','X-Robots-Tag':'noindex, nofollow'};if(!['GET','HEAD'].includes(request.method))return new Response(null,{status:405,headers});if(!value)return new Response(null,{status:404,headers});return new Response(request.method==='HEAD'?null:Uint8Array.from(atob(value),c=>c.charCodeAt(0)),{headers});}};`;await writeFile('dist/worker-photo'+shard+'.mjs',code);console.log('Photo service',shard,Object.keys(photoFiles[shard]).length,'files;',code.length,'bytes');}
console.log('Main worker',Object.keys(files).length,'files;',worker.length,'bytes');
